#!/bin/sh
set -x
set -e
if [ ! -f configure ] ; then sh make_configure; fi
./configure --prefix=/usr --sysconfdir=/etc
make
make -n install
set +x
if [ "`id -u`" != 0 ] ; then
	echo "run make install as root:"
	echo "su root -c 'make install'"
	echo "   OR   "
	echo "sudo make install"
	exit 1
fi
